changelog:
  exclude:
    labels:
      - skip-release-notes
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Build and CI
      labels:
        - ci
        - build
        - release
